import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from './contexts/auth';
import Header from './components/header';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Any additional head elements */}
      </head>
      <body className={inter.className}>
        {/* <AuthProvider> */}
          <Header />
          {children}
        {/* </AuthProvider> */}
      </body>
    </html>
  );
}
